{% set name = "mne-lsl" %}
{% set version = "1.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mne_lsl-{{ version }}.tar.gz
  sha256: 83bc9ae2dbec847bc7d88067ccadf9a7b8f7fc02d785fde033f8af3159f41841

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  skip: true  # [py<311 or (is_abi3 and not is_python_min)]
  entry_points:
    - mne-lsl = mne_lsl._commands.main:run

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pip
    - python
    - python-abi3  # [is_abi3]
    - setuptools >=64.0.0
    - setuptools_scm >=7.0.0
  run:
    - click >=8.1
    - mne-base >=1.6.0
    - numpy >=1.21
    - packaging
    - pooch
    - psutil
    - pyqtgraph
    - python
    - qtpy
    - scipy

test:
  imports:
    - mne_lsl
  commands:
    - pip check
    - mne-lsl sys-info
    - python -c "import mne_lsl; assert mne_lsl.__version__ == '{{ version }}', mne_lsl.__version__"
  requires:
    - python
    - pip

about:
  home: https://mne.tools/mne-lsl
  summary: Real-time framework integrated with MNE-Python for online neuroscience research through LSL-compatible devices.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - src/liblsl/LICENSE
  doc_url: https://mne.tools/mne-lsl
  dev_url: https://github.com/mne-tools/mne-lsl

extra:
  recipe-maintainers:
    - larsoner
    - mscheltienne
