{% set name = "mne-lsl" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mne_lsl-{{ version }}.tar.gz
  sha256: fd721f9fac64968dd92981b3986864b8cdd744ff2917756ef0021ff5dcf444f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mne-lsl = mne_lsl.commands.main:run

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=64.0.0
  run:
    - click >= 8.1
    - distro
    - liblsl
    - mne-base >=1.4.2
    - numpy >=1.21
    - packaging
    - pooch
    - psutil
    - pyqtgraph
    - python >=3.9
    - qtpy
    - requests
    - scipy

test:
  imports:
    - mne_lsl
  commands:
    - pip check
    - mne-lsl sys-info
  requires:
    - pip

about:
  home: https://mne.tools/mne-lsl
  summary: Real-time framework integrated with MNE-Python for online neuroscience research through LSL-compatible devices.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://mne.tools/mne-lsl
  dev_url: https://github.com/mne-tools/mne-lsl

extra:
  recipe-maintainers:
    - mscheltienne
