{% set name = "mne-lsl" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mne_lsl-{{ version }}.tar.gz
  sha256: 7e56223b6c718a06f933a38e41a565e8de43ed6e985cf6cc8e0def2952f12a2b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mne_lsl-sys_info = mne_lsl.commands.sys_info:run
    - mne_lsl_player = mne_lsl.commands.mne_lsl_player:run
    - mne_lsl_stream_viewer = mne_lsl.commands.mne_lsl_stream_viewer:run

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=64.0.0
  run:
    - distro
    - liblsl
    - mne-base >=1.4.2
    - numpy >=1.21
    - packaging
    - pooch
    - psutil
    - pyqtgraph
    - python >=3.9
    - qtpy
    - requests
    - scipy

test:
  imports:
    - mne_lsl
  commands:
    - pip check
    - mne_lsl-sys_info
  requires:
    - pip

about:
  home: https://mne.tools/mne-lsl
  summary: Real-time framework integrated with MNE-Python for online neuroscience research through LSL-compatible devices.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://mne.tools/mne-lsl
  dev_url: https://github.com/mne-tools/mne-lsl

extra:
  recipe-maintainers:
    - mscheltienne
