{% set name = "mne-lsl" %}
{% set version = "1.13.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mne_lsl-{{ version }}.tar.gz
  sha256: b2e18fdd984c602c2c75be9ece0da5ab1f8c1157b6c18ff105afe5c994a1a450

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<310]
  entry_points:
    - mne-lsl = mne_lsl._commands.main:run

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pip
    - python
    - setuptools >=64.0.0
  run:
    - click >=8.1
    - mne-base >=1.6.0
    - numpy >=1.21
    - packaging
    - pooch
    - psutil
    - pyqtgraph
    - python
    - qtpy
    - scipy

test:
  imports:
    - mne_lsl
  commands:
    - pip check
    - mne-lsl sys-info
  requires:
    - pip

about:
  home: https://mne.tools/mne-lsl
  summary: Real-time framework integrated with MNE-Python for online neuroscience research through LSL-compatible devices.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - src/liblsl/LICENSE
  doc_url: https://mne.tools/mne-lsl
  dev_url: https://github.com/mne-tools/mne-lsl

extra:
  recipe-maintainers:
    - larsoner
    - mscheltienne
